
version: 2

models:
  - name: migrating_table.sql
    description: "table migration example"
  - name: incremental_table.sql
    description: "incremental table example"
  - name: addition_view
    description: "Add two numbers"
    columns:
      - name: "id"
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
      - name: "float_value"
        description: "Carry-through of the float value"
        tests:
          - not_null
